//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.16 at 01:31:32 AM IST 
//


package forum.server.persistentlayer;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ConnectionStatusType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ConnectionStatusType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Connected"/>
 *     &lt;enumeration value="Disconected"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ConnectionStatusType")
@XmlEnum
public enum ConnectionStatusType {

    @XmlEnumValue("Connected")
    CONNECTED("Connected"),
    @XmlEnumValue("Disconected")
    DISCONECTED("Disconected");
    private final String value;

    ConnectionStatusType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ConnectionStatusType fromValue(String v) {
        for (ConnectionStatusType c: ConnectionStatusType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
