//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.09 at 01:35:08 AM IST 
//


package forum.server.persistentlayer;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}NamedComponent">
 *       &lt;sequence>
 *         &lt;element name="numOfConnected">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="forumSubjects" type="{}ForumSubject"/>
 *         &lt;/sequence>
 *         &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="registeredUsers" type="{}ForumUser"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "numOfConnected",
    "forumSubjects",
    "registeredUsers"
})
@XmlRootElement(name = "Forum")
public class Forum
    extends NamedComponent
{

    protected int numOfConnected;
    protected List<ForumSubject> forumSubjects;
    protected List<ForumUser> registeredUsers;

    /**
     * Gets the value of the numOfConnected property.
     * 
     */
    public int getNumOfConnected() {
        return numOfConnected;
    }

    /**
     * Sets the value of the numOfConnected property.
     * 
     */
    public void setNumOfConnected(int value) {
        this.numOfConnected = value;
    }

    /**
     * Gets the value of the forumSubjects property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the forumSubjects property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getForumSubjects().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ForumSubject }
     * 
     * 
     */
    public List<ForumSubject> getForumSubjects() {
        if (forumSubjects == null) {
            forumSubjects = new ArrayList<ForumSubject>();
        }
        return this.forumSubjects;
    }

    /**
     * Gets the value of the registeredUsers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the registeredUsers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRegisteredUsers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ForumUser }
     * 
     * 
     */
    public List<ForumUser> getRegisteredUsers() {
        if (registeredUsers == null) {
            registeredUsers = new ArrayList<ForumUser>();
        }
        return this.registeredUsers;
    }

}
