//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.09 at 01:35:08 AM IST 
//


package forum.server.persistentlayer;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ForumThread complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ForumThread">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="startMessage" type="{}ForumMessage"/>
 *         &lt;element name="lastMessage" type="{}ForumMessage"/>
 *         &lt;element name="numOfViews">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="numOfResponses">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ForumThread", propOrder = {
    "startMessage",
    "lastMessage",
    "numOfViews",
    "numOfResponses"
})
public class ForumThread {

    @XmlElement(required = true)
    protected ForumMessage startMessage;
    @XmlElement(required = true)
    protected ForumMessage lastMessage;
    protected int numOfViews;
    protected int numOfResponses;

    /**
     * Gets the value of the startMessage property.
     * 
     * @return
     *     possible object is
     *     {@link ForumMessage }
     *     
     */
    public ForumMessage getStartMessage() {
        return startMessage;
    }

    /**
     * Sets the value of the startMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link ForumMessage }
     *     
     */
    public void setStartMessage(ForumMessage value) {
        this.startMessage = value;
    }

    /**
     * Gets the value of the lastMessage property.
     * 
     * @return
     *     possible object is
     *     {@link ForumMessage }
     *     
     */
    public ForumMessage getLastMessage() {
        return lastMessage;
    }

    /**
     * Sets the value of the lastMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link ForumMessage }
     *     
     */
    public void setLastMessage(ForumMessage value) {
        this.lastMessage = value;
    }

    /**
     * Gets the value of the numOfViews property.
     * 
     */
    public int getNumOfViews() {
        return numOfViews;
    }

    /**
     * Sets the value of the numOfViews property.
     * 
     */
    public void setNumOfViews(int value) {
        this.numOfViews = value;
    }

    /**
     * Gets the value of the numOfResponses property.
     * 
     */
    public int getNumOfResponses() {
        return numOfResponses;
    }

    /**
     * Sets the value of the numOfResponses property.
     * 
     */
    public void setNumOfResponses(int value) {
        this.numOfResponses = value;
    }

}
