//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.01 at 11:06:40 AM IDT 
//


package forum.server.persistentlayer;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ThreadType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ThreadType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="threadID" type="{}NonNegativeLong"/>
 *         &lt;element name="topic" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="startMessageID" type="{}NonNegativeLong"/>
 *         &lt;element name="lastMessageID" type="{}NonNegativeLong"/>
 *         &lt;element name="numOfViews" type="{}NonNegativeLong"/>
 *         &lt;element name="numOfResponses" type="{}NonNegativeLong"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ThreadType", propOrder = {
    "threadID",
    "topic",
    "startMessageID",
    "lastMessageID",
    "numOfViews",
    "numOfResponses"
})
public class ThreadType {

    protected long threadID;
    @XmlElement(required = true)
    protected String topic;
    protected long startMessageID;
    protected long lastMessageID;
    protected long numOfViews;
    protected long numOfResponses;

    /**
     * Gets the value of the threadID property.
     * 
     */
    public long getThreadID() {
        return threadID;
    }

    /**
     * Sets the value of the threadID property.
     * 
     */
    public void setThreadID(long value) {
        this.threadID = value;
    }

    /**
     * Gets the value of the topic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTopic() {
        return topic;
    }

    /**
     * Sets the value of the topic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTopic(String value) {
        this.topic = value;
    }

    /**
     * Gets the value of the startMessageID property.
     * 
     */
    public long getStartMessageID() {
        return startMessageID;
    }

    /**
     * Sets the value of the startMessageID property.
     * 
     */
    public void setStartMessageID(long value) {
        this.startMessageID = value;
    }

    /**
     * Gets the value of the lastMessageID property.
     * 
     */
    public long getLastMessageID() {
        return lastMessageID;
    }

    /**
     * Sets the value of the lastMessageID property.
     * 
     */
    public void setLastMessageID(long value) {
        this.lastMessageID = value;
    }

    /**
     * Gets the value of the numOfViews property.
     * 
     */
    public long getNumOfViews() {
        return numOfViews;
    }

    /**
     * Sets the value of the numOfViews property.
     * 
     */
    public void setNumOfViews(long value) {
        this.numOfViews = value;
    }

    /**
     * Gets the value of the numOfResponses property.
     * 
     */
    public long getNumOfResponses() {
        return numOfResponses;
    }

    /**
     * Sets the value of the numOfResponses property.
     * 
     */
    public void setNumOfResponses(long value) {
        this.numOfResponses = value;
    }

}
